name: Deploy Webpage

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}
      - name: Set up SSH Key for EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST_1 }} >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.EC2_HOST_2 }} >> ~/.ssh/known_hosts
      - name: Install Dependencies and Build App
        run: |
          sudo apt-get install -y nodejs npm
          npm install
          npm run build
      - name: Deploy Build to EC2 Instance 1
        run: |
          scp -o StrictHostKeyChecking=no -r dist/* ec2-user@${{ secrets.EC2_HOST_1 }}:${{secrets.PATH1}}
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST_1 }} << 'EOF'
            sudo systemctl restart nginx
          EOF
      - name: Deploy Build to EC2 Instance 2
        run: |
          scp -o StrictHostKeyChecking=no -r dist/* ec2-user@${{ secrets.EC2_HOST_2 }}:${{secrets.PATH2}}
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST_2 }} << 'EOF'
            sudo systemctl restart nginx
          EOF
